variables:
  NODE_IMAGE: node:18.12.1

stages:
  - Build
  - Lint
  - Test
  - Audit

image: ${NODE_IMAGE}

cache:
  - key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull

install:
  stage: .pre
  cache:
    - key: ${CI_JOB_NAME}
      paths:
        - .npm/
      when: on_success
      policy: pull-push

    - key:
        files:
          - yarn.lock
      paths:
        - node_modules/
      policy: pull-push
  script:
    - yarn --cache-folder .npm

build:
  stage: Build
  script: yarn build
  artifacts:
    paths:
      - dist/

lint:
  stage: Lint
  script:
    - yarn lint

test:
  stage: Test
  script:
    - yarn test

audit:
  stage: Audit
  script: yarn audit
  allow_failure: true
