variables:
  NODE_IMAGE: node:16.13.1

stages:
  - Build
  - Lint
  - Test
  - Audit

build:
  stage: Build
  image: ${NODE_IMAGE}
  before_script: yarn
  script: yarn build
  cache:
    key: cache-${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

lint:
  stage: Lint
  image: ${NODE_IMAGE}
  script:
    - yarn lint

test:
  stage: Test
  image: ${NODE_IMAGE}
  script:
    - yarn
    - yarn test

audit:
  stage: Audit
  image: ${NODE_IMAGE}
  script: yarn audit
  allow_failure: true
