variables:
  NODE_IMAGE: node:16.13.1

stages:
  - Build
  - Lint
  - Test
  - Audit

cache:
  - key:
     files:
        - yarn.lock
    paths: 
      - node_modules/
    policy: pull

install:
  stage: .pre
  image: ${NODE_IMAGE}
  cache:
    - key: ${CI_JOB_NAME}
      paths: 
        - .npm/
      when: on_success
      policy: pull-push
    
    - key:
       files:
          - yarn.lock
      paths: 
        - node_modules/
      policy: pull-push
  script:
    - yarn --cache-folder .npm

  

build:
  stage: Build
  image: ${NODE_IMAGE}
  script: yarn build
  artifacts:
    paths:
      - dist/

lint:
  stage: Lint
  image: ${NODE_IMAGE}
  script:
    - yarn lint

test:
  stage: Test
  image: ${NODE_IMAGE}
  script:
    - yarn
    - yarn test

audit:
  stage: Audit
  image: ${NODE_IMAGE}
  script: yarn audit
  allow_failure: true
